name: Fetch and Commit File

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Fetch file from URL
      env:
        FILE_URL: ${{ secrets.FILE_URL }}
        LOCAL_FILE_NAME: ${{ secrets.LOCAL_FILE_NAME }}
      run: curl -L -o $LOCAL_FILE_NAME $FILE_URL

    - name: Commit and push changes
      env:
        LOCAL_FILE_NAME: ${{ secrets.LOCAL_FILE_NAME }}
      run: |
        if ! git diff --quiet; then
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update file from URL"
          git push origin static-data
          echo "Updated the file"
        fi
